projects:
  app:
    schemaPath: '../src/schemas'
    includes: ['*.graphql']
    extensions:
      endpoints:
        default: 'http://localhost:4000'

  prisma:
    schemaPath: './generated/prisma.graphql'
    extensions:
      prisma: prisma.yml
